#pragma once

#include <Arduino.h>

// Shared glyph record layout for every embedded reader font (legacy Serif /
// OpenDyslexic / Atkinson headers each still define their own identically-
// shaped struct; new fonts generated by tools/generate_embedded_font.py use
// this one directly instead of emitting a fresh duplicate struct per font).
struct EmbeddedFontGlyph {
  uint32_t bitmapOffset;
  int8_t xOffset;
  uint8_t width;
  uint8_t xAdvance;
};

// Descriptor for one rendered font asset (one point size of one family) —
// lets DisplayManager look glyphs up through a data table instead of a
// switch/case per typeface.
struct EmbeddedFontVariant {
  const uint8_t *bitmaps;
  const EmbeddedFontGlyph *glyphs;
  uint8_t firstChar;
  uint8_t lastChar;
  uint8_t height;
};
