#!/usr/bin/env python3
"""Generate firmware/src/app/generated/HelpData.h from tools/help_texts.csv.

Run after editing the CSV:
    python tools/gen_help_texts.py

One row per help topic (the ? pages in the settings). Polish and English
bodies; the other UI languages show the English text. A literal \\n in a
body starts a new paragraph on the device.
"""
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from gen_translations import escape_cpp  # noqa: E402

CSV_PATH = ROOT / "help_texts.csv"
OUT_PATH = ROOT.parent / "firmware/src/app/generated/HelpData.h"


def literal(text: str) -> str:
    parts = text.split("\\n")
    return "\\n".join(escape_cpp(p) for p in parts)


def main() -> None:
    with CSV_PATH.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f, delimiter=";"))
    out = [
        "// AUTO-GENERATED by tools/gen_help_texts.py from tools/help_texts.csv.",
        "// Do not edit by hand.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "enum class HelpTopic : uint8_t {",
    ]
    for row in rows:
        out.append(f"  {row['key']},")
    out += ["  Count,", "};", "", "namespace HelpData {", ""]
    # Same order as UiLanguage (English, Spanish, French, German, Romanian, Polish).
    langs = ["en", "es", "fr", "de", "ro", "pl"]
    out.append("// [topic][UiLanguage][0 = title, 1 = body]")
    out.append(f"inline const char *const kHelp[{len(rows)}][{len(langs)}][2] = {{")
    for row in rows:
        cells = ", ".join(
            f'{{"{literal(row[lang + "_title"] or row["en_title"])}", "{literal(row[lang + "_body"] or row["en_body"])}"}}'
            for lang in langs
        )
        out.append(f"    {{{cells}}},  // {row['key']}")
    out += [
        "};",
        "",
        "inline const char *title(HelpTopic topic, uint8_t langIndex) {",
        "  const uint8_t t = static_cast<uint8_t>(topic);",
        f"  return t < {len(rows)} ? kHelp[t][langIndex < {len(langs)} ? langIndex : 0][0] : \"\";",
        "}",
        "",
        "inline const char *body(HelpTopic topic, uint8_t langIndex) {",
        "  const uint8_t t = static_cast<uint8_t>(topic);",
        f"  return t < {len(rows)} ? kHelp[t][langIndex < {len(langs)} ? langIndex : 0][1] : \"\";",
        "}",
        "",
        "}  // namespace HelpData",
        "",
    ]
    OUT_PATH.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH} ({len(rows)} topics)")


if __name__ == "__main__":
    main()
