#!/usr/bin/env python3
"""Generate firmware/src/app/generated/StarterTitles.h from the starter
library manifest (firmware/tools/generate_starter_library.py).

The wizard's last page lists the six titles of the chosen language before
they are on the card, so it needs their names in the firmware. Run after
changing MANIFEST:
    python tools/gen_starter_titles.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "firmware/tools"))
from gen_translations import escape_cpp  # noqa: E402
import generate_starter_library as library  # noqa: E402

OUT_PATH = ROOT / "firmware/src/app/generated/StarterTitles.h"
# UiLanguage order (Localization.h): English, Spanish, French, German,
# Romanian, Polish.
LANGS = ["en", "es", "fr", "de", "ro", "pl"]


def main() -> None:
    by_lang = {lang: {} for lang in LANGS}
    for entry in library.MANIFEST:
        by_lang[entry["lang"]][entry["slot"]] = entry
    per_language = max(len(slots) for slots in by_lang.values())
    lines = [
        "// AUTO-GENERATED by tools/gen_starter_titles.py -- do not edit by hand.",
        "// Starter library titles per UI language, slot 1 first; the files are",
        "// starter-<lang>-<slot>.rsvp on the release.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "namespace StarterTitles {",
        "",
        "struct Title {",
        "  const char *title;",
        "  const char *author;",
        "};",
        "",
        f"constexpr uint8_t kPerLanguage = {per_language};",
        f"constexpr uint8_t kLanguages = {len(LANGS)};",
        "",
        "// Rows in UiLanguage order: " + ", ".join(LANGS) + ".",
        "constexpr Title kTitles[kLanguages][kPerLanguage] = {",
    ]
    for lang in LANGS:
        lines.append(f"    {{  // {lang}")
        for slot in range(1, per_language + 1):
            entry = by_lang[lang].get(slot)
            if entry is None:
                lines.append('        {"", ""},')
            else:
                lines.append(f'        {{"{escape_cpp(entry["title"])}", "{escape_cpp(entry["author"])}"}},')
        lines.append("    },")
    lines += ["};", "", "}  // namespace StarterTitles", ""]
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
