#!/usr/bin/env python3
"""Generate firmware/src/app/generated/TranslationsData.h from tools/translations.csv.

Run manually after editing tools/translations.csv:
    python tools/gen_translations.py

The enum declarations (TrKey/TrKey2/TrKey3) in firmware/src/app/Translations.h
stay the single source of truth for which keys exist and in what order --
this script reads them and cross-checks every enum member has exactly one CSV
row, and every CSV row matches a declared enum member. Adding a translation
still means adding the enum entry by hand plus a CSV row; this script only
replaces the hand-written switch bodies with generated lookup tables.
"""
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRANSLATIONS_H = ROOT / "firmware/src/app/Translations.h"
LOCALIZATION_H = ROOT / "firmware/src/app/Localization.h"
DICTAPHONE_PLUGIN_CPP = ROOT / "firmware/src/plugins/builtin/DictaphonePlugin.cpp"
CSV_PATH = ROOT / "tools/translations.csv"
OUT_PATH = ROOT / "firmware/src/app/generated/TranslationsData.h"

# Column order in the CSV vs. array row order, which must match the
# UiLanguage enum in Localization.h (English=0, Spanish=1, French=2,
# German=3, Romanian=4, Polish=5). DictaphonePlugin.cpp's own DictStr enum
# uses the same 6-language ordering (see its comment) despite living outside
# the app -- the generated table for it goes in the same output file/
# namespace since DeviceServicesBridge.cpp (which reads it on the plugin's
# behalf via the PluginDisplayService::pluginTr function pointer) already
# includes app/Translations.h.
CSV_LANG_COLUMNS = ["en", "es", "fr", "de", "ro", "pl"]

TABLES = [
    (TRANSLATIONS_H, "TrKey", "trKeyLookup"),
    (TRANSLATIONS_H, "TrKey2", "trKey2Lookup"),
    (TRANSLATIONS_H, "TrKey3", "trKey3Lookup"),
    (LOCALIZATION_H, "UiText", "uiTextLookup"),
    (DICTAPHONE_PLUGIN_CPP, "DictStr", "dictStrLookup"),
]


def parse_enum_order(enum_name: str, text: str, source_path: Path) -> list[str]:
    m = re.search(r"enum class " + enum_name + r" : uint8_t \{(.*?)\};", text, re.DOTALL)
    if not m:
        sys.exit(f"ERROR: could not find enum class {enum_name} in {source_path}")
    keys = []
    for line in m.group(1).splitlines():
        line = line.split("//", 1)[0].strip()
        if not line:
            continue
        keys.append(line.rstrip(",").strip())
    return keys


def escape_cpp(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    header_texts = {
        path: path.read_text(encoding="utf-8")
        for path in {source_path for source_path, _, _ in TABLES}
    }

    with CSV_PATH.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f, delimiter=";"))

    csv_by_key = {}
    for row in rows:
        key = row["key"]
        if key in csv_by_key:
            sys.exit(f"ERROR: duplicate CSV key {key}")
        csv_by_key[key] = row

    out = []
    out.append("// AUTO-GENERATED by tools/gen_translations.py from tools/translations.csv.")
    out.append("// Do not edit by hand -- edit the CSV and rerun the generator.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("namespace TranslationsData {")
    out.append("")

    used_keys = set()

    for source_path, enum_name, lookup_fn in TABLES:
        enum_keys = parse_enum_order(enum_name, header_texts[source_path], source_path)
        rows_for_table = []
        for key_name in enum_keys:
            csv_key = f"{enum_name}.{key_name}"
            row = csv_by_key.get(csv_key)
            if row is None:
                sys.exit(f"ERROR: enum {enum_name}::{key_name} has no CSV row '{csv_key}'")
            used_keys.add(csv_key)
            values = [escape_cpp(row[col]) for col in CSV_LANG_COLUMNS]
            rows_for_table.append((key_name, values))

        out.append(f"inline const char *{lookup_fn}(uint8_t keyIndex, uint8_t langIndex) {{")
        out.append(f"  static const char *const kTable[{len(rows_for_table)}][6] = {{")
        for key_name, values in rows_for_table:
            literal = ", ".join(f'"{v}"' for v in values)
            out.append(f"      {{{literal}}},  // {key_name}")
        out.append("  };")
        out.append("  return kTable[keyIndex][langIndex];")
        out.append("}")
        out.append("")

    orphan_keys = set(csv_by_key.keys()) - used_keys
    if orphan_keys:
        sys.exit(f"ERROR: CSV rows with no matching enum member: {sorted(orphan_keys)}")

    out.append("}  // namespace TranslationsData")
    out.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(out), encoding="utf-8", newline="\n")
    total_keys = sum(
        len(parse_enum_order(enum_name, header_texts[source_path], source_path))
        for source_path, enum_name, _ in TABLES
    )
    print(f"wrote {OUT_PATH} ({total_keys} keys x 6 languages)")


if __name__ == "__main__":
    main()
