#!/usr/bin/env python3
"""Generates src/text/UnicodeFold.h from the slot map in src/text/LatinText.h.

The reader keeps text in a single-byte encoding (ASCII + Latin-1 + custom
slots for Polish, Czech, Romanian, Baltic... letters). This header adds:

  * the reverse map (storage byte -> Unicode) so the companion API can hand
    the Flower app real UTF-8 instead of raw storage bytes;
  * composition of a base letter with a following combining mark (NFD text,
    e.g. "z" + U+0307 from some ODT/EPUB exports) into the precomposed letter;
  * a Latin transliteration of Cyrillic and Greek, which the reader's fonts
    don't have (before this those letters were dropped from the text).

Run: python tools/gen_unicode_fold.py
"""

import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LATIN = ROOT / "src" / "text" / "LatinText.h"
OUTPUT = ROOT / "src" / "text" / "UnicodeFold.h"

src = LATIN.read_text(encoding="utf-8")
body = re.search(r"inline bool customSlotForCodepoint.*?default:", src, re.S).group(0)
slot_for_cp = {int(cp, 16): int(slot, 16) for cp, slot in re.findall(r"case (0x[0-9A-Fa-f]+):\s*slot = (0x[0-9A-Fa-f]+);", body)}
rep = re.search(r"inline bool isRepurposedLatin1Byte.*?default:", src, re.S).group(0)
repurposed = {int(v, 16) for v in re.findall(r"case (0x[0-9A-Fa-f]+):", rep)}


def storage_byte(cp: int):
    if 32 <= cp <= 126:
        return cp
    if cp in slot_for_cp:
        return slot_for_cp[cp]
    if 0xA1 <= cp <= 0xFF and cp not in repurposed:
        return cp
    return None


cp_for_byte = {}
for value in range(256):
    cp = None
    if 32 <= value <= 126:
        cp = value
    elif value >= 0xA1 and value not in repurposed:
        cp = value
    cp_for_byte[value] = cp
for cp, slot in slot_for_cp.items():
    cp_for_byte[slot] = cp

# Combining marks -> precomposed letters the storage encoding has.
compose = []
bases = [cp for cp in cp_for_byte.values() if cp is not None and chr(cp).isalpha()]
for mark in range(0x0300, 0x0370):
    for base in sorted(set(bases)):
        composed = unicodedata.normalize("NFC", chr(base) + chr(mark))
        if len(composed) == 1 and storage_byte(ord(composed)) is not None:
            compose.append((base, mark, ord(composed)))
compose.sort()

# Cyrillic: scholarly transliteration (Ukrainian values for г/и, which keeps
# Ukrainian text closest to how it sounds; Russian stays readable).
CYR = {
    "а": "a", "б": "b", "в": "v", "г": "h", "ґ": "g", "д": "d", "е": "e", "є": "je", "ж": "ž",
    "з": "z", "и": "y", "і": "i", "ї": "ji", "й": "j", "к": "k", "л": "l", "м": "m", "н": "n",
    "о": "o", "п": "p", "р": "r", "с": "s", "т": "t", "у": "u", "ф": "f", "х": "ch", "ц": "c",
    "ч": "č", "ш": "š", "щ": "šč", "ь": "", "ю": "ju", "я": "ja", "ё": "ë", "ы": "y", "э": "è",
    "ъ": "", "ў": "ŭ", "ђ": "đ", "ј": "j", "љ": "lj", "њ": "nj", "ћ": "ć", "џ": "dž", "ѓ": "ǵ",
    "ќ": "ḱ", "ѕ": "dz",
}
GRK = {
    "α": "a", "β": "v", "γ": "g", "δ": "d", "ε": "e", "ζ": "z", "η": "i", "θ": "th", "ι": "i",
    "κ": "k", "λ": "l", "μ": "m", "ν": "n", "ξ": "x", "ο": "o", "π": "p", "ρ": "r", "σ": "s",
    "ς": "s", "τ": "t", "υ": "y", "φ": "f", "χ": "ch", "ψ": "ps", "ω": "o",
    "ά": "á", "έ": "é", "ή": "í", "ί": "í", "ό": "ó", "ύ": "ý", "ώ": "ó", "ϊ": "ï", "ϋ": "ÿ",
    "ΐ": "ï", "ΰ": "ÿ",
}


def fold_to_storage(text: str) -> str:
    out = []
    for ch in text:
        b = storage_byte(ord(ch))
        if b is None:
            # Letters the encoding lacks (ǵ, ḱ, ŭ...) lose the accent.
            base = unicodedata.normalize("NFD", ch)[0]
            b = storage_byte(ord(base))
        if b is not None:
            out.append(b)
    return "".join(f"\\x{b:02X}" for b in out)


translit = []
for table in (CYR, GRK):
    for lower, latin in table.items():
        translit.append((ord(lower), fold_to_storage(latin)))
        upper = lower.upper()
        if len(upper) == 1 and upper != lower:
            cap = latin[:1].upper() + latin[1:] if latin else ""
            translit.append((ord(upper), fold_to_storage(cap)))
translit.sort()

lines = []
lines.append("#pragma once")
lines.append("")
lines.append("// AUTO-GENERATED by tools/gen_unicode_fold.py -- do not edit by hand.")
lines.append("// Reverse storage map, combining-mark composition and Cyrillic/Greek")
lines.append("// transliteration for the reader's single-byte text (see LatinText.h).")
lines.append("")
lines.append("#include <Arduino.h>")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("namespace UnicodeFold {")
lines.append("")
lines.append("// Unicode code point for each storage byte, 0 where the byte is not text.")
lines.append("constexpr uint16_t kCodepointForByte[256] = {")
row = []
for value in range(256):
    row.append(f"0x{(cp_for_byte[value] or 0):04X}")
for i in range(0, 256, 8):
    lines.append("    " + ", ".join(row[i:i + 8]) + ",")
lines.append("};")
lines.append("")
lines.append("inline uint32_t codepointForStorageByte(uint8_t value) { return kCodepointForByte[value]; }")
lines.append("")
lines.append("struct Composition {")
lines.append("  uint16_t base;")
lines.append("  uint16_t mark;")
lines.append("  uint16_t composed;")
lines.append("};")
lines.append("")
lines.append(f"constexpr Composition kCompositions[] = {{")
for base, mark, composed in compose:
    lines.append(f"    {{0x{base:04X}, 0x{mark:04X}, 0x{composed:04X}}},")
lines.append("};")
lines.append("")
lines.append("inline bool isCombiningMark(uint32_t codepoint) { return codepoint >= 0x0300 && codepoint <= 0x036F; }")
lines.append("")
lines.append("// Precomposed letter for base + combining mark, or 0.")
lines.append("inline uint32_t compose(uint32_t base, uint32_t mark) {")
lines.append("  for (const Composition &entry : kCompositions) {")
lines.append("    if (entry.base == base && entry.mark == mark) {")
lines.append("      return entry.composed;")
lines.append("    }")
lines.append("  }")
lines.append("  return 0;")
lines.append("}")
lines.append("")
lines.append("struct Transliteration {")
lines.append("  uint16_t codepoint;")
lines.append("  const char *latin;  // storage bytes")
lines.append("};")
lines.append("")
lines.append("constexpr Transliteration kTransliterations[] = {")
for cp, latin in translit:
    lines.append(f"    {{0x{cp:04X}, \"{latin}\"}},  // {chr(cp)}")
lines.append("};")
lines.append("")
lines.append("// Latin spelling (storage bytes) for a Cyrillic or Greek letter, nullptr otherwise.")
lines.append("inline const char *transliterate(uint32_t codepoint) {")
lines.append("  if (codepoint < 0x0370 || codepoint > 0x04FF) {")
lines.append("    return nullptr;")
lines.append("  }")
lines.append("  for (const Transliteration &entry : kTransliterations) {")
lines.append("    if (entry.codepoint == codepoint) {")
lines.append("      return entry.latin;")
lines.append("    }")
lines.append("  }")
lines.append("  return nullptr;")
lines.append("}")
lines.append("")
lines.append("inline void appendUtf8(String &out, uint32_t codepoint) {")
lines.append("  if (codepoint < 0x80) {")
lines.append("    out += static_cast<char>(codepoint);")
lines.append("  } else if (codepoint < 0x800) {")
lines.append("    out += static_cast<char>(0xC0 | (codepoint >> 6));")
lines.append("    out += static_cast<char>(0x80 | (codepoint & 0x3F));")
lines.append("  } else {")
lines.append("    out += static_cast<char>(0xE0 | (codepoint >> 12));")
lines.append("    out += static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F));")
lines.append("    out += static_cast<char>(0x80 | (codepoint & 0x3F));")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("// True when `text` has multi-byte UTF-8 sequences and nothing else above 0x7F.")
lines.append("inline bool looksLikeUtf8(const String &text) {")
lines.append("  bool multiByte = false;")
lines.append("  for (size_t i = 0; i < text.length();) {")
lines.append("    const uint8_t lead = static_cast<uint8_t>(text[i]);")
lines.append("    size_t extra = 0;")
lines.append("    if (lead < 0x80) {")
lines.append("      ++i;")
lines.append("      continue;")
lines.append("    } else if ((lead & 0xE0) == 0xC0 && lead >= 0xC2) {")
lines.append("      extra = 1;")
lines.append("    } else if ((lead & 0xF0) == 0xE0) {")
lines.append("      extra = 2;")
lines.append("    } else if ((lead & 0xF8) == 0xF0 && lead <= 0xF4) {")
lines.append("      extra = 3;")
lines.append("    } else {")
lines.append("      return false;")
lines.append("    }")
lines.append("    for (size_t k = 1; k <= extra; ++k) {")
lines.append("      if (i + k >= text.length() || (static_cast<uint8_t>(text[i + k]) & 0xC0) != 0x80) {")
lines.append("        return false;")
lines.append("      }")
lines.append("    }")
lines.append("    multiByte = true;")
lines.append("    i += extra + 1;")
lines.append("  }")
lines.append("  return multiByte;")
lines.append("}")
lines.append("")
lines.append("// UTF-8 for text that may be in the reader's storage encoding (the index,")
lines.append("// chapter markers, reader-converted books) or already UTF-8 (app uploads).")
lines.append("inline String toUtf8(const String &text) {")
lines.append("  bool plain = true;")
lines.append("  for (size_t i = 0; i < text.length(); ++i) {")
lines.append("    const uint8_t value = static_cast<uint8_t>(text[i]);")
lines.append("    if (value >= 0x80 || (value < 0x20 && codepointForStorageByte(value) != 0)) {")
lines.append("      plain = false;")
lines.append("      break;")
lines.append("    }")
lines.append("  }")
lines.append("  if (plain || looksLikeUtf8(text)) {")
lines.append("    return text;")
lines.append("  }")
lines.append("  String out;")
lines.append("  out.reserve(text.length() + text.length() / 4);")
lines.append("  for (size_t i = 0; i < text.length(); ++i) {")
lines.append("    const uint8_t value = static_cast<uint8_t>(text[i]);")
lines.append("    const uint32_t codepoint = codepointForStorageByte(value);")
lines.append("    if (codepoint != 0) {")
lines.append("      appendUtf8(out, codepoint);")
lines.append("    } else if (value < 0x80) {")
lines.append("      out += static_cast<char>(value);")
lines.append("    }")
lines.append("  }")
lines.append("  return out;")
lines.append("}")
lines.append("")
lines.append("}  // namespace UnicodeFold")
lines.append("")

OUTPUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUTPUT} ({len(compose)} compositions, {len(translit)} transliterations)")
